---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "kube-applier"
    namespace: "kube-system"
  spec: 
    ports: 
      - name: "service"
        port: 80
        targetPort: 2020
    selector: 
      app: "kube-applier"
