// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/box/kube-applier/run

package run

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of RunnerInterface interface
type MockRunnerInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockRunnerInterfaceRecorder
}

// Recorder for MockRunnerInterface (not exported)
type _MockRunnerInterfaceRecorder struct {
	mock *MockRunnerInterface
}

func NewMockRunnerInterface(ctrl *gomock.Controller) *MockRunnerInterface {
	mock := &MockRunnerInterface{ctrl: ctrl}
	mock.recorder = &_MockRunnerInterfaceRecorder{mock}
	return mock
}

func (_m *MockRunnerInterface) EXPECT() *_MockRunnerInterfaceRecorder {
	return _m.recorder
}

func (_m *MockRunnerInterface) Run() (*Result, error) {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].(*Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRunnerInterfaceRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}
