// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/box/kube-applier/run

package run

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of CheckerInterface interface
type MockCheckerInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockCheckerInterfaceRecorder
}

// Recorder for MockCheckerInterface (not exported)
type _MockCheckerInterfaceRecorder struct {
	mock *MockCheckerInterface
}

func NewMockCheckerInterface(ctrl *gomock.Controller) *MockCheckerInterface {
	mock := &MockCheckerInterface{ctrl: ctrl}
	mock.recorder = &_MockCheckerInterfaceRecorder{mock}
	return mock
}

func (_m *MockCheckerInterface) EXPECT() *_MockCheckerInterfaceRecorder {
	return _m.recorder
}

func (_m *MockCheckerInterface) ShouldRun(_param0 *Result) (bool, error) {
	ret := _m.ctrl.Call(_m, "ShouldRun", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCheckerInterfaceRecorder) ShouldRun(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ShouldRun", arg0)
}
