// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/box/kube-applier/metrics

package metrics

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of PrometheusInterface interface
type MockPrometheusInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockPrometheusInterfaceRecorder
}

// Recorder for MockPrometheusInterface (not exported)
type _MockPrometheusInterfaceRecorder struct {
	mock *MockPrometheusInterface
}

func NewMockPrometheusInterface(ctrl *gomock.Controller) *MockPrometheusInterface {
	mock := &MockPrometheusInterface{ctrl: ctrl}
	mock.recorder = &_MockPrometheusInterfaceRecorder{mock}
	return mock
}

func (_m *MockPrometheusInterface) EXPECT() *_MockPrometheusInterfaceRecorder {
	return _m.recorder
}

func (_m *MockPrometheusInterface) UpdateFileSuccess(_param0 string, _param1 bool) {
	_m.ctrl.Call(_m, "UpdateFileSuccess", _param0, _param1)
}

func (_mr *_MockPrometheusInterfaceRecorder) UpdateFileSuccess(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateFileSuccess", arg0, arg1)
}

func (_m *MockPrometheusInterface) UpdateRunLatency(_param0 float64, _param1 bool) {
	_m.ctrl.Call(_m, "UpdateRunLatency", _param0, _param1)
}

func (_mr *_MockPrometheusInterfaceRecorder) UpdateRunLatency(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateRunLatency", arg0, arg1)
}
