// Code generated by MockGen. DO NOT EDIT.
// Source: prometheus.go

// Package metrics is a generated GoMock package.
package metrics

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPrometheusInterface is a mock of PrometheusInterface interface
type MockPrometheusInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPrometheusInterfaceMockRecorder
}

// MockPrometheusInterfaceMockRecorder is the mock recorder for MockPrometheusInterface
type MockPrometheusInterfaceMockRecorder struct {
	mock *MockPrometheusInterface
}

// NewMockPrometheusInterface creates a new mock instance
func NewMockPrometheusInterface(ctrl *gomock.Controller) *MockPrometheusInterface {
	mock := &MockPrometheusInterface{ctrl: ctrl}
	mock.recorder = &MockPrometheusInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrometheusInterface) EXPECT() *MockPrometheusInterfaceMockRecorder {
	return m.recorder
}

// UpdateNamespaceSuccess mocks base method
func (m *MockPrometheusInterface) UpdateNamespaceSuccess(arg0 string, arg1 bool) {
	m.ctrl.Call(m, "UpdateNamespaceSuccess", arg0, arg1)
}

// UpdateNamespaceSuccess indicates an expected call of UpdateNamespaceSuccess
func (mr *MockPrometheusInterfaceMockRecorder) UpdateNamespaceSuccess(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamespaceSuccess", reflect.TypeOf((*MockPrometheusInterface)(nil).UpdateNamespaceSuccess), arg0, arg1)
}

// UpdateRunLatency mocks base method
func (m *MockPrometheusInterface) UpdateRunLatency(arg0 float64, arg1 bool) {
	m.ctrl.Call(m, "UpdateRunLatency", arg0, arg1)
}

// UpdateRunLatency indicates an expected call of UpdateRunLatency
func (mr *MockPrometheusInterfaceMockRecorder) UpdateRunLatency(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunLatency", reflect.TypeOf((*MockPrometheusInterface)(nil).UpdateRunLatency), arg0, arg1)
}

// UpdateFailedResultSummary mocks base method
func (m *MockPrometheusInterface) UpdateFailedResultSummary(failures map[string]string) {
	m.ctrl.Call(m, "UpdateFailedResultSummary", failures)
}

// UpdateFailedResultSummary indicates an expected call of UpdateFailedResultSummary
func (mr *MockPrometheusInterfaceMockRecorder) UpdateFailedResultSummary(failures interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFailedResultSummary", reflect.TypeOf((*MockPrometheusInterface)(nil).UpdateFailedResultSummary), failures)
}
